version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      example-network:
        ipv4_address: 172.16.238.10

  postgres:
    image: postgres
    container_name: postgresql_container
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_INITDB_ARGS: "--encoding=win1250 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    networks:
      example-network:
        ipv4_address: 172.16.238.11

  backend:
    image: netcore
    container_name: backend_container
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      example-network:
        ipv4_address: 172.16.238.12
    
    ports:
      - 3000:3000
    networks:
      example-network:
        ipv4_address: 172.16.238.13

  frontend:
    image: nextjs
    container_name: frontend_container
    build:
      context: ./frontend
      args:
        - http_proxy=http://egvbrvproxy1v1.egv.at:8081
        - https_proxy=http://egvbrvproxy1v1.egv.at:8081
    restart: unless-stopped
    
    ports:
      - 3000:3000
    networks:
      example-network:
        ipv4_address: 172.16.238.13
        
  nginx:
    image: arm32v6/nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      example-network:
        ipv4_address: 172.16.238.15
        
networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
